SELECT * FROM tab;
SELECT * FROM tb_book;
SELECT * FROM tb_category;
SELECT * FROM tb_publisher;
SELECT * FROM TB_ATTACH;

UPDATE TB_ATTACH SET BOOK_UID = 8 WHERE ATTACH_UID = 11;

CREATE OR REPLACE VIEW view_book AS
SELECT  
		tbk.BOOK_UID bookUid, tbk.BOOK_SUBJECT subject, tbk.BOOK_AUTHOR author, 
		tbk.BOOK_CONTENT content, tbk.BOOK_PRICE price, tbk.BOOK_PUBDATE pubdate, tbk.BOOK_REGDATE regdate, 
		tbk.BOOK_ISBN isbn, tbk.CATEGORY_UID categoryUid, tbk.PUBLISHER_UID pubUid,
		tpb.PUBLISHER_NAME pubName, tct.CATEGORY_NAME categoryName,
		tat.ATTACH_SERVERNAME serName, tat.ATTACH_URI uri
	FROM tb_book tbk
	LEFT OUTER JOIN TB_PUBLISHER tpb 
	ON tbk.PUBLISHER_UID = tpb.PUBLISHER_UID 
	LEFT OUTER JOIN TB_CATEGORY tct 
	ON tbk.CATEGORY_UID = tct.CATEGORY_UID 
	LEFT OUTER JOIN TB_ATTACH tat
	ON tbk.BOOK_UID = tat.BOOK_UID 
	ORDER BY tbk.BOOK_UID DESC;

SELECT * FROM view_book;	


SELECT *
FROM 
(SELECT rownum AS rnum, vb.* 
FROM VIEW_BOOK vb)
WHERE RNUM >= 1 AND RNUM < 1 + 5
;

SELECT count(*) FROM TB_BOOK;

UPDATE TB_BOOK 
SET 
	BOOK_SUBJECT = '바뀌었지', BOOK_AUTHOR = '이장훈', BOOK_CONTENT = '바뀌었다구', BOOK_PUBDATE = SYSDATE, BOOK_ISBN = 34262, CATEGORY_UID = 2, PUBLISHER_UID = 1 
WHERE BOOK_UID = 10;

SELECT BOOK_UID, BOOK_SUBJECT, BOOK_AUTHOR, BOOK_CONTENT, BOOK_PUBDATE, BOOK_REGDATE, BOOK_ISBN, CATEGORY_UID, PUBLISHER_UID 
FROM tb_book 
ORDER BY BOOK_UID DESC;

SELECT 
		BOOK_UID bookUid, BOOK_SUBJECT subject, BOOK_AUTHOR author, BOOK_CONTENT content, BOOK_PUBDATE pubdate, BOOK_REGDATE regdate, BOOK_ISBN isbn, CATEGORY_UID categoryUid, PUBLISHER_UID pubUid 
	FROM tb_book 
	ORDER BY BOOK_UID DESC;

INSERT INTO TB_CATEGORY 
	(CATEGORY_UID, CATEGORY_NAME, CATEGORY_PARENT) 
VALUES
	(1, '컴퓨터', null);

INSERT INTO TB_CATEGORY 
	(CATEGORY_UID, CATEGORY_NAME, CATEGORY_PARENT) 
VALUES
	(2, '자바', 2);

INSERT INTO TB_CATEGORY 
	(CATEGORY_UID, CATEGORY_NAME, CATEGORY_PARENT) 
VALUES
	(3, 'C', 1);

INSERT INTO TB_PUBLISHER 
	(PUBLISHER_UID, PUBLISHER_NAME, PUBLISHER_NUM, PUBLISHER_REP, PUBLISHER_CONTACT, PUBLISHER_ADDRESS) 
VALUES
	(publisher_seq.nextval, '길벗', '02-6522-6511', '김재훈', '구매부', '서울 서초구');

INSERT INTO TB_PUBLISHER 
	(PUBLISHER_UID, PUBLISHER_NAME, PUBLISHER_NUM, PUBLISHER_REP, PUBLISHER_CONTACT, PUBLISHER_ADDRESS) 
VALUES
	(publisher_seq.nextval, '한빛', '02-1232-6511', '이재훈', '총부부', '서울 동작구');

INSERT INTO TB_BOOK 
	(BOOK_UID, BOOK_SUBJECT, BOOK_AUTHOR, BOOK_CONTENT, BOOK_PUBDATE, BOOK_REGDATE, BOOK_ISBN, CATEGORY_UID, PUBLISHER_UID) 
VALUES
	(book_seq.nextval, '자바의 정석', '제임스', '자바를 배워봅시다', SYSDATE, SYSDATE, '12435', 1, 2);

INSERT INTO TB_BOOK 
	(BOOK_UID, BOOK_SUBJECT, BOOK_AUTHOR, BOOK_CONTENT, BOOK_PUBDATE, BOOK_REGDATE, BOOK_ISBN, CATEGORY_UID, PUBLISHER_UID) 
VALUES
	(book_seq.nextval, 'C를 배워보자', '고슬링', 'C를 배워봅시다', SYSDATE, SYSDATE, '12435', 1, 1);